# Generated by Django 2.2 on 2021-05-18 20:10

import autoslug.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default='def', max_length=255, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Розовый'), (1, 'Белый'), (2, 'Светло-синий'), (3, 'Голубой'), (4, 'Светло-Зеленый'), (5, 'Коричневый'), (6, 'Серый')], default=3, verbose_name='Цвет продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 18, 20, 10, 2, 693827, tzinfo=utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='default', verbose_name='Описание товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скидка в процентах'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_structure',
            field=models.PositiveSmallIntegerField(choices=[(7, 'Атлас'), (8, 'Батист'), (9, 'Бенгалин'), (10, 'Букле'), (11, 'Бязь'), (12, 'Полиэстер')], default=12, verbose_name='Состав ткани'),
        ),
        migrations.AddField(
            model_name='product',
            name='fashion',
            field=models.PositiveSmallIntegerField(choices=[(13, 'А-Силуэт'), (14, 'Завышенная талия'), (15, 'Ампир'), (16, 'Греческий стиль'), (17, 'Ретро стиль'), (18, 'Винтаж стиль')], default=13, verbose_name='Фасон'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.PositiveSmallIntegerField(choices=[(42, '82-85'), (44, '86-89'), (46, '90-93'), (48, '94-97'), (50, '98-102'), (52, '103-107'), (54, '108-113'), (56, '114-119')], default=50, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=9, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_range',
            field=models.PositiveSmallIntegerField(choices=[(42, 42), (44, 44), (46, 46), (48, 48), (50, 50), (52, 52), (54, 54), (56, 56), (58, 58), (60, 60)], default=50, verbose_name='Размерный ряд'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='sasdasd', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование товара'),
        ),
    ]
