# Generated by Django 2.2 on 2021-05-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона магазина')),
                ('email', models.EmailField(max_length=100, verbose_name='Почтовый адрес магазина')),
                ('location', models.CharField(max_length=200, verbose_name='Адрес магазина')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
