# Generated by Django 2.2 on 2021-05-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_products',
            field=models.ManyToManyField(to='product.Product', verbose_name='Товар в избранном'),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
