# Generated by Django 2.2 on 2021-05-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210514_2034'),
        ('users', '0003_auto_20210514_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='product',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='product',
            field=models.ManyToManyField(to='product.Product', verbose_name='Товар в избранном'),
        ),
    ]
